language: java
jdk:
  - openjdk8

git:
  quiet: true

before_install:
  - sudo chmod 777 .travis/hbase-init.sh

install: true

before_script:
  - .travis/hbase-init.sh

script:
  - mvn clean compile > /dev/null 2>&1
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=nimbo3_Keenbo

cache:
  directories:
    - $HOME/.m2
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "nimbo3-1"
    token:
      secure: ${SONAR_TOKEN}
