language: java
jdk:
  - openjdk8

git:
  quiet: true

before_install:
  - sudo chmod 777 .travis/hbase-init.sh

install: true

before_script:
  - .travis/hbase-init.sh

script:
  - mvn clean compile > /dev/null 2>&1
  - mvn test

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
